name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/checkout@v4
      - run: pnpm install
      - run: pnpm run build.data
        env:
          KEY_KAKAO: ${{ secrets.KEY_KAKAO }}
      - run: pnpm run build
        env:
          GOOGLE_ANALYTICS_ID: UA-159081219-1
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./out