name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pnpm install
      - run: pnpm run build.data
        env:
          KEY_KAKAO: ${{ secrets.KEY_KAKAO }}
      - run: pnpm run build
        env:
          GOOGLE_ANALYTICS_ID: UA-159081219-1
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          forceOrphan: true
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./out